//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Input
{
    public partial class @GameInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""GenericActions"",
            ""id"": ""404ad226-e74c-4f35-9d18-5d533168754b"",
            ""actions"": [
                {
                    ""name"": ""TapAction"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9e1b375f-7d10-44ae-9bf8-f8b89e797d21"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e07af80e-93b3-4338-a4f7-ce4d430fe137"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""TouchScreen"",
                    ""action"": ""TapAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""TouchScreen"",
            ""bindingGroup"": ""TouchScreen"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // GenericActions
            m_GenericActions = asset.FindActionMap("GenericActions", throwIfNotFound: true);
            m_GenericActions_TapAction = m_GenericActions.FindAction("TapAction", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GenericActions
        private readonly InputActionMap m_GenericActions;
        private List<IGenericActionsActions> m_GenericActionsActionsCallbackInterfaces = new List<IGenericActionsActions>();
        private readonly InputAction m_GenericActions_TapAction;
        public struct GenericActionsActions
        {
            private @GameInput m_Wrapper;
            public GenericActionsActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @TapAction => m_Wrapper.m_GenericActions_TapAction;
            public InputActionMap Get() { return m_Wrapper.m_GenericActions; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GenericActionsActions set) { return set.Get(); }
            public void AddCallbacks(IGenericActionsActions instance)
            {
                if (instance == null || m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Add(instance);
                @TapAction.started += instance.OnTapAction;
                @TapAction.performed += instance.OnTapAction;
                @TapAction.canceled += instance.OnTapAction;
            }

            private void UnregisterCallbacks(IGenericActionsActions instance)
            {
                @TapAction.started -= instance.OnTapAction;
                @TapAction.performed -= instance.OnTapAction;
                @TapAction.canceled -= instance.OnTapAction;
            }

            public void RemoveCallbacks(IGenericActionsActions instance)
            {
                if (m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGenericActionsActions instance)
            {
                foreach (var item in m_Wrapper.m_GenericActionsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GenericActionsActions @GenericActions => new GenericActionsActions(this);
        private int m_TouchScreenSchemeIndex = -1;
        public InputControlScheme TouchScreenScheme
        {
            get
            {
                if (m_TouchScreenSchemeIndex == -1) m_TouchScreenSchemeIndex = asset.FindControlSchemeIndex("TouchScreen");
                return asset.controlSchemes[m_TouchScreenSchemeIndex];
            }
        }
        public interface IGenericActionsActions
        {
            void OnTapAction(InputAction.CallbackContext context);
        }
    }
}
