//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Input
{
    public partial class @GameInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""GenericActions"",
            ""id"": ""404ad226-e74c-4f35-9d18-5d533168754b"",
            ""actions"": [
                {
                    ""name"": ""TouchButton"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1d3827f5-39e0-453f-a10f-c456e829227a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""43ed5bbe-765a-4e48-a859-bf928afee906"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // GenericActions
            m_GenericActions = asset.FindActionMap("GenericActions", throwIfNotFound: true);
            m_GenericActions_TouchButton = m_GenericActions.FindAction("TouchButton", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GenericActions
        private readonly InputActionMap m_GenericActions;
        private List<IGenericActionsActions> m_GenericActionsActionsCallbackInterfaces = new List<IGenericActionsActions>();
        private readonly InputAction m_GenericActions_TouchButton;
        public struct GenericActionsActions
        {
            private @GameInput m_Wrapper;
            public GenericActionsActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @TouchButton => m_Wrapper.m_GenericActions_TouchButton;
            public InputActionMap Get() { return m_Wrapper.m_GenericActions; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GenericActionsActions set) { return set.Get(); }
            public void AddCallbacks(IGenericActionsActions instance)
            {
                if (instance == null || m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Add(instance);
                @TouchButton.started += instance.OnTouchButton;
                @TouchButton.performed += instance.OnTouchButton;
                @TouchButton.canceled += instance.OnTouchButton;
            }

            private void UnregisterCallbacks(IGenericActionsActions instance)
            {
                @TouchButton.started -= instance.OnTouchButton;
                @TouchButton.performed -= instance.OnTouchButton;
                @TouchButton.canceled -= instance.OnTouchButton;
            }

            public void RemoveCallbacks(IGenericActionsActions instance)
            {
                if (m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGenericActionsActions instance)
            {
                foreach (var item in m_Wrapper.m_GenericActionsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GenericActionsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GenericActionsActions @GenericActions => new GenericActionsActions(this);
        public interface IGenericActionsActions
        {
            void OnTouchButton(InputAction.CallbackContext context);
        }
    }
}
